language: php

# We want to test against PHP 5.3/5.4/5.5
php:
  - 5.5
  - 5.4
  - 5.3
#  - 5.6
#  - hhvm

# Separate different test suites
env:
  matrix:
    # PDO Mysql
    - TEST_SUITE=IntegrationTests MYSQL_ADAPTER=PDO_MYSQL
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL
    - TEST_SUITE=CoreTests MYSQL_ADAPTER=PDO_MYSQL
    # Mysqli
    - TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI
    # Javascript tests
    - TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    - TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
  global:
    - secure: "AMhZmPZx4SUcuZRBzGHlQPxzM4D8FvFB3UThDa52gbi9KIBrwcumzV2VGi6B\n5fgjwtB4XTE1In7qhY2HMikPWBmWYYOQ5QcMPJsqqHt4iMmahx8WKzne6NOk\nNpqAuje/fulNGeP2LJZi0nrub3Fh4VwXaOvpNloKNQN/2JuqPtM="
    - secure: "DySde80fX3dw0osGY5s5lGiGLjMleUkkONsuRDC4xjT1hAQP94FGHpPXVZV8\nAQY0s8MQmcK2eRLOQrmE9Bh1XXbGqh40s66XhSWq0hulFHxQH5OLaZXccFeu\n5WxGkHXnNDIc+CVhXW/IIbHZPO1K6hffS8fuvP1o6mYgxwFL6Xw="

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
  exclude:
    # Javascript tests need to run only on one PHP version
    - php: 5.4
      env: TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    - php: 5.5
      env: TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    - php: 5.6
      env: TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    - php: hhvm
      env: TEST_SUITE=JavascriptTests MYSQL_ADAPTER=PDO_MYSQL
    # AngularJS tests need to run only on one PHP version
    - php: 5.4
      env: TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
    - php: 5.5
      env: TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
    - php: 5.6
      env: TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
    - php: hhvm
      env: TEST_SUITE=AngularJSTests MYSQL_ADAPTER=PDO_MYSQL
    # Only run Mysqli tests on PHP 5.5
    - php: 5.4
      env: TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - php: 5.4
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - php: 5.4
      env: TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI
    - php: 5.5
      env: TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - php: 5.5
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - php: 5.5
      env: TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI
    - php: 5.6
      env: TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - php: 5.6
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - php: 5.6
      env: TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI
    - php: hhvm
      env: TEST_SUITE=IntegrationTests MYSQL_ADAPTER=MYSQLI
    - php: hhvm
      env: TEST_SUITE=PluginTests MYSQL_ADAPTER=MYSQLI
    - php: hhvm
      env: TEST_SUITE=CoreTests MYSQL_ADAPTER=MYSQLI

script: ./travis.sh

before_script:
  - mysql --version
  - mysql -e "SELECT VERSION();"
  - mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION'" # Travis default
  # Uncomment to enable sql_mode STRICT_TRANS_TABLES (new default in Mysql 5.6)
  #- mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'"
  - mysql -e "SELECT @@sql_mode;"
  # Setup Piwik stack
  - ./tests/travis/initiate_ui_tests.sh
  - composer self-update
  - composer install
  - uname -a
  - date
  - php -r "var_dump(gd_info());"
  - mysql -e 'create database piwik_tests;'
  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh
  - cd tests/PHPUnit

after_success:
  - cd $TRAVIS_BUILD_DIR
  - ./tests/travis/generate_docs.sh

after_script:
  - cat /var/log/nginx/error.log
  - cat $TRAVIS_BUILD_DIR/tmp/php-fpm.log
  - cat $TRAVIS_BUILD_DIR/tmp/logs/piwik.log
  - cd $TRAVIS_BUILD_DIR
  - ./tests/travis/upload_artifacts.sh

notifications:
  irc:
    skip_join: true
    on_success: change
    channels:
      - "irc.freenode.org#piwik-dev"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
  #email:
  # if we specify piwik-builds@piwik.org then the developer doesn't get notified
  #  - piwik-builds@piwik.org
  # this is a missing feature by Travis to notify both list and committer
