language: php

# We want to test against 
php:
  - 5.5
  - 5.4
  - 5.3

env:
  matrix:
    - TEST_SUITE=PluginTests
    - TEST_SUITE=CoreTests
    - TEST_SUITE=IntegrationTests

script: phpunit --configuration phpunit.xml --testsuite $TEST_SUITE --coverage-text

before_script:
  - mysql -e 'create database piwik_test;'
  - ./tests/travis.sh
  - ./tests/travis/setup_webserver.sh
  - cd tests/PHPUnit

notifications:
  irc:
    skip_join: true
    on_success: change
    channels:
      - "irc.freenode.org#piwik-dev"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
  email:
    - piwik-builds@piwik.org
