name: 'Handle inactive PRs - closing message'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          debug-only: false
          start-date: 2021-03-01T00:00:00Z
          days-before-pr-stale: 42
          days-before-pr-close: -1
          days-before-issue-stale: -1
          days-before-issue-close: -1
          exempt-pr-labels: Do not close
          stale-pr-message: This PR was last updated more than one month ago, maybe it's time to close it. Please check if there is anything we still can do or close this PR. ping @matomo-org/core-reviewers
          stale-pr-label: Stale for long
