# Action for running tests
# This file has been automatically created.
# To recreate it you can run this command
# ./console generate:test-action --php-versions="7.2,8.2"

name: Matomo Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - '**.x-dev'
      - 'next_release'
  workflow_dispatch:

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

concurrency:
  group: php-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PHP:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        type: [ 'UnitTests', 'SystemTestsPlugins', 'SystemTestsCore', 'IntegrationTestsCore', 'IntegrationTestsPlugins' ]
        php: [ '7.2', '8.2', '8.3' ]
        engine: [ 'Mysql', 'Mariadb' ]
        adapter: [ 'PDO_MYSQL', 'MYSQLI' ]
        exclude:
          - php: '7.2'
            engine: 'Mariadb'
          - php: '8.2'
            engine: 'Mysql'
          - php: '8.3'
            engine: 'Mariadb'
          - php: '7.2'
            adapter: 'MYSQLI'
          - php: '8.2'
            adapter: 'MYSQLI'
          - php: '8.3'
            adapter: 'PDO_MYSQL'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          persist-credentials: false
          submodules: true
          path: matomo
      - name: running tests
        uses: matomo-org/github-action-tests@tidb
        with:
          test-type: ${{ matrix.type }}
          mysql-driver: ${{ matrix.adapter }}
          mysql-engine: ${{ matrix.engine }}
          php-version: ${{ matrix.php }}
          redis-service: true
          artifacts-pass: ${{ secrets.ARTIFACTS_PASS }}
          upload-artifacts: ${{ matrix.php == '7.2' }}
          testomatio: ${{ secrets.TESTOMATIO_INTEGRATION }}
  Javascript:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          persist-credentials: false
          submodules: true
          path: matomo
      - name: running tests
        uses: matomo-org/github-action-tests@tidb
        with:
          test-type: 'JS'
          php-version: '7.2'
          node-version: '12'
  Client:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          persist-credentials: false
          submodules: true
          path: matomo
      - name: running tests
        uses: matomo-org/github-action-tests@tidb
        with:
          test-type: 'Client'
          node-version: '16'
          mysql-service: false
  UI:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        parts: [ 0,1,2,3 ]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
          submodules: true
          path: matomo
      - name: running tests
        uses: matomo-org/github-action-tests@tidb
        with:
          testomatio: ${{ secrets.TESTOMATIO }}
          ui-test-options: '--num-test-groups=4 --test-group=${{ matrix.parts }}'
          test-type: 'UI'
          php-version: '7.2'
          node-version: '16'
          redis-service: true
          artifacts-pass: ${{ secrets.ARTIFACTS_PASS }}
          upload-artifacts: true
