name: Matomo Tests

on:
  pull_request:

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none
concurrency:
  group: php-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  PHP:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        command: [ 'UnitTests', 'SystemTestsPlugins' ,'SystemTestsCore' , 'IntegrationTestsCore', 'IntegrationTestsPlugins' ]
        type: [ 'PHP' ]
        php: [ '7.2', '8.1' ]
        adapter: [ 'PDO_MYSQL', 'MYSQLI' ]
        exclude:
          - php: '8.1'
            adapter: 'PDO_MYSQL'
          - php: '7.2'
            adapter: 'MYSQLI'
    steps:
      - name: running tests
        uses: matomo-org/github-action-tests@v1
        with:
          test-type: ${{ matrix.type }}
          mysql-driver: ${{ matrix.adapter }}
          php-version: ${{ matrix.php }}
          test-command: ${{ matrix.command }}
          redis-service: true
          git-sha: ${{ github.event.pull_request.head.sha }}
  Javascript:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.2' ]
        tests: [ 'JS' ]
        node: [ '12' ]
        adapter: [ 'PDO_MYSQL' ]

    steps:
      - name: running tests
        uses: matomo-org/github-action-tests@v1
        with:
          test-type: ${{ matrix.tests }}
          mysql-driver: ${{ matrix.adapter }}
          php-version: ${{ matrix.php }}
          node-version: ${{ matrix.node }}
          git-sha: ${{ github.event.pull_request.head.sha }}
  Angular:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        type: [ 'Angular' ]
        node: [ '16' ]
        adapter: [ 'PDO_MYSQL' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: false
          submodules: recursive

      - name: running tests
        uses: matomo-org/github-action-tests@v1
        with:
          test-type: ${{ matrix.type }}
          mysql-driver: ${{ matrix.adapter }}
          php-version: ${{ matrix.php }}
          test-command: ${{ matrix.tests }}
          mysql-service: false
  UI:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        tests: [ 'UI' ]
        php: [ '7.2' ]
        parts: [ 0,1,2 ]
        adapter: [ 'PDO_MYSQL' ]
        node: [ '16' ]
    steps:
      - name: running tests
        uses: matomo-org/github-action-tests@v1
        with:
          test-type: ${{ matrix.tests }}
          mysql-driver: ${{ matrix.adapter }}
          php-version: ${{ matrix.php }}
          test-command: ${{ matrix.parts }}
          run_number: ${{ github.run_number }}
          node-version: ${{ matrix.node }}
          repository: ${{ github.repository }}
          artifect_pass: ${{ secrets.ARTIFACTS_PASS }}
          ref: ${{ github.event.pull_request.base.ref }}
          run_id: ${{ github.run_id }}
          php-memory: "-1"
          redis-service: true
          git-sha: ${{ github.event.pull_request.head.sha }}


